#!/bin/sh
#
# Start/stop dhcpcd
#

DAEMON=/sbin/wpa_supplicant
CONFIG=/etc/wpa_supplicant.conf

[ -f $CONFIG ] || exit 0

case "$1" in
  start)
	echo "Starting wpa_suppliacnt@wlan0 ..."
	start-stop-daemon -S -x "$DAEMON" -- -i wlan0 -c /etc/wpa_supplicant.conf &
	;;
  stop)
	echo "Stopping wpa_suppliant@wlan0..."
	killall wpa_supplicant
	;;
  reload|force-reload)
	;;
  restart)
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac
