#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /bin/ipshowonscreen ] || exit 0

start() {
	echo "start ip show on screen"
	/bin/ipshowonscreen &
}


case "$1" in
  start)
	start
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?

